Create Module Get-LocalUsers.ps1
davehull/Kansa pull request #217
Opened 2022-11-18 08:58 UTC by ahans003

Create new conf module Get-LocalUsers.ps1

2022-11-20 02:30 UTC, davehull requested changes
Thanks for contributing! Please see my note about the obsolete output directive.

2022-11-20 02:30 UTC, davehull commented on Modules/Config/Get-LocalUsers.ps1
> +OUTPUT tsv
You shouldn't need (nor include) this bit in the collector code anymore. See this blog post re: the `-OutputFormat` command-line parameter, which made this directive in the modules obsolete.

2022-11-20 20:23 UTC, ahans003 commented
Requested changes have been completed

2022-11-22 02:14 UTC, davehull approved these changes

2022-11-22 02:14 UTC, merged